In [2]:
# -*- coding: utf-8 -*-
import matplotlib as mpl
import math as math
import pandas as pd
import numpy as np
import scipy.stats as spstats
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline

# import IPython.core.display as di
# di.display_html('<script>jQuery(function() {if (jQuery("body.notebook_app").length == 0) { jQuery(".input_area").toggle(); jQuery(".prompt").toggle();}});</script>', raw=True)

# 2018.1.23 Notebook 
李曦嵘　　634602068@qq.com　　武汉大学电子信息学院

## 3 QR分解的应用

### 3.1 QR算法求特征值

![](http://img.blog.csdn.net/20150305201229278)

>知乎：
[为什么矩阵QR分解迭代的主对角会最终收敛到特征值？](https://www.zhihu.com/question/54455860)

In [4]:
print(''.center(50,'='))
a = np.matrix([[2, 1],
               [1, 2]])
print('a=',a)

print('QR分解'.center(50,'='))

q,r=np.linalg.qr(a, 'complete')

b = np.around([np.dot(q,r)], decimals = 2) 

c = np.around([np.dot(q,q.T)], decimals = 10) 

d = np.around([np.dot(r,q)], decimals = 10)

print('q=',q,'r=',r,'q*r=',b,'q*q=',c,'r*q=',d,sep='\n\n')

print('end'.center(50,'='))

###############################################

print('特征值与特征向量'.center(50,'='))
value, v=np.linalg.eig(a)
print('A的特征向量为:\n', v,'\nA的特征值为:\n', value)
print('QR算法求特征值'.center(50,'='))

def is_same (a,b):
    n = len(a)
    for i in range(n):
        if math.fabs(a[i]-b[i]) > 1e-10:
            return False
    return True

times = 0
b = a
while (times==0) or (not is_same(np.diag(b), v)):
    v = np.diag(b)
    q,r = np.linalg.qr(b)
    b = np.dot(r,q)
    times += 1
    
print('迭代次数：\n', times,'\n特征值：\n', np.diag(b))
print('end'.center(50,'='))

a= [[2 1]
 [1 2]]
=======================QR分解=======================
q=

[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

r=

[[-2.23606798 -1.78885438]
 [ 0.          1.34164079]]

q*r=

[[[ 2.  1.]
  [ 1.  2.]]]

q*q=

[[[ 1. -0.]
  [-0.  1.]]]

r*q=

[[[ 2.8 -0.6]
  [-0.6  1.2]]]
=======================end========================
=====================特征值与特征向量=====================
A的特征向量为:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 
A的特征值为:
 [ 3.  1.]
=====================QR算法求特征值=====================
迭代次数：
 12 
特征值：
 [ 3.  1.]
=======================end========================


### 3.2 QR分解求矩阵的逆

原理：  

$$
A^{-1}=(QR)^{-1}=R^{-1}Q^{-1}=R^{-1}Q^{T}
$$

转换为求一个上三角矩阵的逆。

https://www.zhihu.com/question/54455860 
http://blog.csdn.net/xueyingxue001/article/details/51830188